"use client";

import { useState } from "react";
import type { SalesDirectorPanelData } from "@/lib/ai/salesDirector";
import type { DirectorVerdict, Channel } from "@/lib/ai/engines/director";
import type { QualDimensionKey } from "@/lib/ai/engines/qualification";

// ─── Small helpers ──────────────────────────────────────────────────────────────

function CopyBtn({ text }: { text: string }) {
  const [done, setDone] = useState(false);
  return (
    <button
      type="button"
      onClick={() => navigator.clipboard.writeText(text).then(() => { setDone(true); setTimeout(() => setDone(false), 1800); })}
      className="text-[10px] px-1.5 py-0.5 rounded bg-white/70 hover:bg-white text-gray-600 border border-gray-200 shrink-0 transition-colors"
    >
      {done ? "✓ Copied" : "Copy"}
    </button>
  );
}

const VERDICT_STYLE: Record<DirectorVerdict, { bg: string; text: string; ring: string; emoji: string }> = {
  Escalate:    { bg: "bg-purple-600",  text: "text-white", ring: "ring-purple-300",  emoji: "⭐" },
  PushToClose: { bg: "bg-green-600",   text: "text-white", ring: "ring-green-300",   emoji: "🔑" },
  Nurture:     { bg: "bg-amber-500",   text: "text-white", ring: "ring-amber-300",   emoji: "🌱" },
  Revive:      { bg: "bg-blue-600",    text: "text-white", ring: "ring-blue-300",    emoji: "🔄" },
  Drop:        { bg: "bg-gray-500",    text: "text-white", ring: "ring-gray-300",    emoji: "🛑" },
};
const CHANNEL_EMOJI: Record<Channel, string> = { Call: "📞", WhatsApp: "💬", Email: "📧", Meeting: "🤝", SiteVisit: "🏢" };
const URGENCY_STYLE: Record<string, string> = { Now: "bg-red-100 text-red-700", Today: "bg-orange-100 text-orange-700", ThisWeek: "bg-amber-100 text-amber-700", Later: "bg-gray-100 text-gray-500" };
const SIGNAL_STYLE: Record<string, string> = { Strong: "bg-green-100 text-green-700", Moderate: "bg-amber-100 text-amber-700", Weak: "bg-red-100 text-red-600", Unknown: "bg-gray-100 text-gray-400" };
const QUAL_LABEL: Record<QualDimensionKey, string> = {
  budget: "Budget", authority: "Authority", need: "Need", timeline: "Timeline", intent: "Intent",
  portfolio: "Portfolio", investmentKnowledge: "Knowledge", visitStatus: "Visit", engagement: "Engaged",
};

function List({ items, tone = "gray" }: { items: string[]; tone?: "red" | "blue" | "gray" }) {
  const dot = tone === "red" ? "text-red-400" : tone === "blue" ? "text-blue-400" : "text-gray-300";
  if (!items?.length) return <span className="text-gray-300 text-xs italic">—</span>;
  return (
    <ul className="space-y-1">
      {items.map((it, i) => (
        <li key={i} className="flex gap-1.5 text-xs text-gray-700 leading-snug">
          <span className={`${dot} shrink-0 mt-0.5 select-none`}>•</span>
          <span>{it}</span>
        </li>
      ))}
    </ul>
  );
}

function SubCard({ title, emoji, badge, children }: { title: string; emoji: string; badge?: React.ReactNode; children: React.ReactNode }) {
  return (
    <div className="rounded-lg border border-gray-200 bg-white p-3">
      <div className="flex items-center justify-between mb-2">
        <span className="text-xs font-bold text-gray-800">{emoji} {title}</span>
        {badge}
      </div>
      {children}
    </div>
  );
}

// ─── Main panel ─────────────────────────────────────────────────────────────────

export default function AISalesDirectorPanel({ data }: { data: SalesDirectorPanelData }) {
  const { director: d, qualification: q, coaching: c, followup: f, inventory: inv, meta } = data;
  const vs = VERDICT_STYLE[d.verdict];

  return (
    <div className="rounded-xl border border-gray-200 bg-gradient-to-b from-gray-50 to-white shadow-sm overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between gap-2 px-4 py-3 border-b border-gray-200 bg-white">
        <div className="flex items-center gap-2">
          <span className="text-sm font-bold text-gray-900">🎯 AI Sales Director</span>
          <span className={`text-[10px] px-2 py-0.5 rounded-full font-bold ${vs.bg} ${vs.text}`}>{vs.emoji} {d.verdict}</span>
          <span className={`text-[10px] px-1.5 py-0.5 rounded-full font-medium ${URGENCY_STYLE[d.urgency] ?? ""}`}>{d.urgency}</span>
        </div>
        <span className="text-[10px] px-2 py-0.5 rounded-full bg-gray-100 text-gray-400 border border-gray-200" title={`Generated by: ${meta.provider}`}>
          {meta.mocked ? "heuristic preview" : meta.provider}
        </span>
      </div>

      {/* Director verdict — the headline call */}
      <div className="px-4 py-3">
        <p className="text-sm text-gray-800 font-medium leading-snug">{d.verdictReason}</p>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-3">
          <div className="rounded-lg bg-red-50/60 border border-red-100 p-2.5">
            <div className="text-[10px] font-bold text-red-600 uppercase tracking-wide mb-1">⚠ What&apos;s missing</div>
            <List items={d.whatsMissing} tone="red" />
          </div>
          <div className="rounded-lg bg-blue-50/60 border border-blue-100 p-2.5">
            <div className="text-[10px] font-bold text-blue-600 uppercase tracking-wide mb-1">❓ Ask next</div>
            <List items={d.whatToAskNext} tone="blue" />
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-3">
          <div className="rounded-lg bg-gray-50 border border-gray-200 p-2.5">
            <div className="text-[10px] font-bold text-gray-500 uppercase tracking-wide mb-1">▶ Next action</div>
            <p className="text-xs text-gray-800 leading-snug">{d.nextAction}</p>
          </div>
          <div className="rounded-lg bg-gray-50 border border-gray-200 p-2.5">
            <div className="text-[10px] font-bold text-gray-500 uppercase tracking-wide mb-1">{CHANNEL_EMOJI[d.channel]} Channel — {d.channel}</div>
            <p className="text-xs text-gray-600 leading-snug">{d.channelReason}</p>
          </div>
        </div>

        {d.escalate.should && (
          <div className="mt-3 rounded-lg bg-purple-50 border border-purple-200 p-2.5">
            <span className="text-xs font-bold text-purple-800">⭐ Escalate to {d.escalate.to}</span>
            {d.escalate.why && <span className="text-xs text-purple-600"> — {d.escalate.why}</span>}
          </div>
        )}

        {/* Ready-to-send opener */}
        <div className="mt-3 rounded-lg bg-white border border-gray-200 p-2.5">
          <div className="flex items-center justify-between mb-1">
            <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wide">✍ Opening line</span>
            <CopyBtn text={d.openingLine} />
          </div>
          <p className="text-xs text-gray-700 italic leading-snug">&ldquo;{d.openingLine}&rdquo;</p>
        </div>
      </div>

      {/* Supporting engines */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-3 px-4 pb-4">
        {/* Qualification */}
        <SubCard
          title="Qualification"
          emoji="📊"
          badge={<span className={`text-[10px] px-2 py-0.5 rounded-full font-semibold ${q.overall === "Qualified" ? "bg-green-100 text-green-700" : q.overall === "Unqualified" ? "bg-red-100 text-red-600" : "bg-amber-100 text-amber-700"}`}>{q.totalScore}/100 · {q.overall}</span>}
        >
          <div className="grid grid-cols-3 gap-1 mb-2">
            {(Object.keys(QUAL_LABEL) as QualDimensionKey[]).map((k) => (
              <div key={k} className={`text-center rounded px-1 py-1 ${SIGNAL_STYLE[q.dimensions[k]?.signal] ?? "bg-gray-50"}`} title={q.dimensions[k]?.evidence}>
                <div className="text-[9px] font-medium opacity-80">{QUAL_LABEL[k]}</div>
                <div className="text-[11px] font-bold">{q.dimensions[k]?.score ?? 0}</div>
              </div>
            ))}
          </div>
          <p className="text-[11px] text-gray-500"><span className="font-semibold text-gray-600">Biggest gap:</span> {q.biggestGap}</p>
        </SubCard>

        {/* Coaching */}
        <SubCard
          title="Agent Coaching"
          emoji="🎓"
          badge={<span className={`text-[10px] px-2 py-0.5 rounded-full font-semibold ${c.grade === "Strong" ? "bg-green-100 text-green-700" : c.grade === "Average" ? "bg-amber-100 text-amber-700" : "bg-red-100 text-red-600"}`}>{c.grade}</span>}
        >
          <p className="text-[11px] text-gray-700 font-medium mb-1.5">{c.headline}</p>
          <div className="text-[10px] font-bold text-gray-400 uppercase tracking-wide mb-0.5">Missed</div>
          <List items={c.whatAgentMissed} />
          <div className="text-[10px] font-bold text-gray-400 uppercase tracking-wide mt-2 mb-0.5">Coach&apos;s note</div>
          <p className="text-[11px] text-gray-600 italic">{c.oneThingToDoBetter}</p>
        </SubCard>

        {/* Follow-up */}
        <SubCard
          title="Follow-up"
          emoji="⏱"
          badge={
            <span className={`text-[10px] px-2 py-0.5 rounded-full font-semibold ${f.lastFollowupQuality === "Strong" ? "bg-green-100 text-green-700" : f.lastFollowupQuality === "Average" ? "bg-amber-100 text-amber-700" : f.lastFollowupQuality === "None" ? "bg-gray-100 text-gray-400" : "bg-red-100 text-red-600"}`}>
              {f.lastFollowupQuality}{f.overdue ? " · overdue" : ""}
            </span>
          }
        >
          <p className="text-[11px] text-gray-500 mb-2">{f.reason} · {f.recommendedChannel}</p>
          <div className="rounded bg-gray-50 border border-gray-200 p-2">
            <div className="flex items-center justify-between mb-1">
              <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wide">Ready to send</span>
              <CopyBtn text={f.draftMessage} />
            </div>
            <p className="text-[11px] text-gray-700 leading-snug">{f.draftMessage}</p>
          </div>
        </SubCard>

        {/* Inventory */}
        <SubCard
          title="Inventory Match"
          emoji="🏢"
          badge={<span className={`text-[10px] px-2 py-0.5 rounded-full font-semibold ${inv.matchStatus === "GoodMatch" ? "bg-green-100 text-green-700" : inv.matchStatus === "PartialMatch" ? "bg-amber-100 text-amber-700" : "bg-gray-100 text-gray-500"}`}>{inv.matchStatus.replace(/([A-Z])/g, " $1").trim()}</span>}
        >
          {inv.suggestedProjects.length === 0 ? (
            <div className="text-[11px] text-gray-400">
              <span className="font-bold text-gray-300 uppercase tracking-widest text-[10px] block mb-1">Not enough data</span>
              {inv.sourcingGaps[0] ?? "Capture budget + unit type to match inventory."}
            </div>
          ) : (
            <div className="space-y-1.5">
              {inv.suggestedProjects.map((p, i) => (
                <div key={i} className="rounded border border-gray-100 p-2">
                  <div className="text-[11px] font-semibold text-gray-800">{p.name}</div>
                  <p className="text-[10px] text-gray-500">{p.why}</p>
                  <p className="text-[10px] text-blue-700 italic mt-0.5">💬 {p.pitch}</p>
                </div>
              ))}
              {inv.sourcingGaps.length > 0 && <p className="text-[10px] text-amber-600">⚠ {inv.sourcingGaps[0]}</p>}
            </div>
          )}
        </SubCard>
      </div>
    </div>
  );
}
